### ISSUE TITLE
Ignoring Content-type

### ISSUE THREAD

**Issue by panyapro** [cossme/grinder#32]
Hello.
I have some api, which require set Content-type for GET request without request data. But grinder discard it
`create_request(self, test, headers):
        request = HTTPRequest(url=self.host_url)
        headers.append(NVPair("Content-type", "application/json; charset=utf-8"))
        headers.append(NVPair("Accept", "application/json"))
        headers.append(NVPair("Protection-Token", "Protection-Token-Value"))
        request.setHeaders(headers)
        return request`
I have found it place - HTTPClient.HTTPConnection#assembleHeaders
Could you fix it

**Comment by solcyr** [comment]
Hi @panyapro,
A fix has been done for this issue in the 4.0.2-SNAPSHOT release.
